#!/bin/sh
# 拉取server分支分代码到master分支；
# 通知中控机已收到代码；
export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
export HOME="/home/git"
export zPathOnHost="__PROJ_PATH"

cd ${zPathOnHost}_SHADOW
export GIT_DIR="${zPathOnHost}_SHADOW/.git"
\ls -a | grep -Ev '^(\.|\.\.|\.git)$' | xargs rm -rf
git stash
git checkout server
git branch -D master
git checkout -b master
git reset -q --hard `git log -1 --format=%H`

cd $zPathOnHost
export GIT_DIR="${zPathOnHost}/.git"
\ls -a | grep -Ev '^(\.|\.\.|\.git)$' | xargs rm -rf
git stash
git checkout server
zCurSig=`git log -1 --format=%H`
printf "`date +%s` $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM" > ____mark.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
git add ____mark.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
git commit -m "____MARK____"
git branch -D master
git checkout -b master
git reset -q --hard $zCurSig  # 工作区不需要附带 MARK 文件

# 'B' 用于标识这是布署状态回复，'A' 用于标识远程主机初始化状态回复
sh -x ${zPathOnHost}_SHADOW/scripts/zclient_reply.sh "__MASTER_ADDR" "__MASTER_PORT" "B" > /tmp/____post-deploy.sh 2>&1

# 布署完成之后需要执行的动作：<项目名称.sh>
sh __PROJ_PATH/____post-deploy.sh &
echo -e "#refresh date: `date`\ncurrent sig: ${zCurSig}" >> __PROJ_PATH/____post-deploy.sh

# 自我更新
cp ${zPathOnHost}_SHADOW/scripts/post-update ${zPathOnHost}/.git/hooks/post-update
