#!/bin/sh
# 拉取server分支分代码到master分支；
# 通知中控机已收到代码；
export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
export HOME="/home/git"
export zPathOnHost='__PROJ_PATH'

cd ${zPathOnHost}_SHADOW
export GIT_DIR="${zPathOnHost}_SHADOW/.git"
git add --all .
git commit -m "_"
git checkout server
git checkout -b TMP
git reset -q --hard
git branch -M master

cd $zPathOnHost
export GIT_DIR="${zPathOnHost}/.git"
git add --all .
git commit -m "_"
git checkout server
zCurSig=`git log -1 --format=%H`
printf "`date +%s` $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM" > ____MARK____XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXZ
git add ____MARK____XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXZ
git commit -m "____MARK____"
git checkout -b TMP
git reset -q --hard $zCurSig  # 工作区不需要附带 MARK 文件
git branch -M master

cd ${zPathOnHost}_SHADOW
# 'B' 用于标识这是布署状态回复，'A' 用于标识远程主机初始化状态回复
./scripts/zclient_reply.sh '__MASTER_ADDR' '__MASTER_PORT' 'B'
# i=0
# while [[ 3 -gt $i ]]; do
#     sleep 1
#     ./scripts/zclient_reply.sh '__MASTER_ADDR' '__MASTER_PORT' 'B'
#     let i++
# done

# 布署完成之后需要执行的动作：<项目名称.sh>
sh __PROJ_PATH/____post-deploy.sh
echo '[refresh date]: `date`' >> __PROJ_PATH/____post-deploy.sh
