#!/bin/sh
# 拉取server分支分代码到master分支；
# 通知中控机已收到代码；

export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

zPathOnHost="__PROJ_PATH"
sh ${zPathOnHost}_SHADOW/tools/zpost-update.sh
